# Generated by Django 4.1 on 2022-08-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
