# Generated by Django 4.1 on 2022-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre del Cliente'),
        ),
    ]
